amqp:
  config:
    auto-create: true
  host: rabbit
  port: 5672
  username: adm_videos
  password: 123456

logging:
  level:
    ROOT: info

mysql:
  username: ${mysql.username}
  password: ${mysql.password}
  schema: ${mysql.database}
  url: ${mysql.host}:${mysql.port}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration