amqp:
  admin:
    auto-create: ${AMQP_CONFIGURATION_AUTO_CREATE}
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}

mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
