## valid uuid = b8ee6449-b662-4245-9f12-430dfb74df6c
@jwtToken = xxx

@baseUrl = http://localhost:8080/api

###
####################### Category ################### 
###
# @name createCategory
POST {{baseUrl}}/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Category 1",
    "description": "Description 1"
}

###

@categoryId = {{createCategory.response.body.id}}

###
GET {{baseUrl}}/categories HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
GET {{baseUrl}}/categories/{{categoryId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
# @name updateCategory
PUT {{baseUrl}}/categories/{{categoryId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Category 1 Updated",
    "description": "Description 1 Updated",
    "is_active": true
}


###
# @name deleteCategory
DELETE {{baseUrl}}/categories/{{categoryId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
####################### Genre ################### 
###

# @name create
POST {{baseUrl}}/genres HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Genre 1",
    "categories_id": [
    "f32cfb61-97ff-4fe4-8792-9d1e892bc66b",
    "9fe50ce8-adbd-404d-8d2b-3501c0c95b9d"
    ]
}

@genreId = {{create.response.body.id}}

###
GET {{baseUrl}}/genres HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
GET {{baseUrl}}/genres/{{genreId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
# @name updateGenre
PUT {{baseUrl}}/genres/{{genreId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Genre 1 Updated",
    "is_active": true
}

###
# @name deleteCategory
DELETE {{baseUrl}}/genres/{{genreId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
####################### Cast Member ################### 
###

# @name createCastMember
POST {{baseUrl}}/cast_members HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "John Doe",
    "type": "DIRECTOR" 
}

@castMemberId = {{createCastMember.response.body.id}}

###
GET {{baseUrl}}/cast_members HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
GET {{baseUrl}}/cast_members/{{castMemberId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}

###
# @name updateGenre
PUT  {{baseUrl}}/cast_members/{{castMemberId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "John Doe",
    "type": "ACTOR"
}

###
# @name deleteCategory
DELETE {{baseUrl}}/cast_members/{{castMemberId}} HTTP/1.1
Authorization: Bearer {{jwtToken}}