services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/home/dev/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8.0.30-debian
        environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=adm_videos
        security_opt:
        - seccomp:unconfined
        ports:
        - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping",  "-h", "localhost"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s