services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/home/node/app
        ports:
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway