services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/home/dev/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            mysql:
                condition: service_healthy
    qas:
        profiles: ["qas"]
        build:
            context: .
            dockerfile: Dockerfile.qas
        restart: unless-stopped
        env_file:
            - .env.qas
        ports:
            - 8081:8080
        extra_hosts:
            - host.docker.internal:host-gateway

    mysql:
        image: mysql:8.0.30-debian
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=adm_videos
        security_opt:
            - seccomp:unconfined
        ports:
            - 3306:3306
        extra_hosts:
            - host.docker.internal:host-gateway
        
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s

    rabbit:
        container_name: adm_videos_rabbitmq
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=adm_videos
            - RABBITMQ_DEFAULT_PASS=123456
        ports:
            - 15672:15672
            - 5672:5672
        extra_hosts:
            - host.docker.internal:host-gateway
