services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/home/dev/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8.0.30-debian
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=adm_videos
        security_opt:
            - seccomp:unconfined
        volumes:
            - mysql-data:/var/lib/mysql
            - ./.docker/init-mysql/create-keycloak-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        ports:
            - 3306:3306
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s

    rabbit:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=adm_videos
            - RABBITMQ_DEFAULT_PASS=123456
        ports:
            - 15672:15672
            - 5672:5672
        extra_hosts:
            - host.docker.internal:host-gateway

    keycloak:
        image: quay.io/keycloak/keycloak:22.0.5
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=mysql
            - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
            - KC_DB_USERNAME=root
            - KC_DB_PASSWORD=123456
        ports:
            - 8443:8080
        depends_on:
            mysql:
                condition: service_healthy
        extra_hosts:
            - host.docker.internal:host-gateway

volumes:
    mysql-data:
